struct { const gchar *language; const gchar *group; RegExTypes type; const gchar *regex; } REGEX_BUILTIN[] =
{
  { "", "", REGEX_TYPE_ENTER, "^\\s*Entering directory\\s+'(?<directory>[^']+)'\\s*$" },
  { "", "", REGEX_TYPE_ERROR, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):\\s*warning:\\s*(?<message>.+)$" },
  { "", "", REGEX_TYPE_LEAVE, "^\\s*Leaving directory\\s+'(?<directory>[^']+)'\\s*$" },
  { "", "", REGEX_TYPE_WARNING, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*warning:\\s*(?<message>.+)$" },
  { "C", "clang", REGEX_TYPE_ERROR, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*.*error:\\s*(?<message>.+)$" },
  { "C", "clang", REGEX_TYPE_EXTENSION, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*note:\\s*(?<message>.+)$" },
  { "C", "clang", REGEX_TYPE_WARNING, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*warning:\\s*(?<message>.+)$" },
  { "C", "gcc", REGEX_TYPE_ERROR, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*.*error:\\s*(?<message>.+)$" },
  { "C", "gcc", REGEX_TYPE_EXTENSION, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*note:\\s*(?<message>.+)$" },
  { "C", "gcc", REGEX_TYPE_WARNING, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*warning:\\s*(?<message>.+)$" },
  { "C", "linker", REGEX_TYPE_ERROR, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):\\s*(?<message>undefined.*)$" },
  { "C++", "clang", REGEX_TYPE_ERROR, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*.*error:\\s*(?<message>.+)$" },
  { "C++", "clang", REGEX_TYPE_EXTENSION, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*note:\\s*(?<message>.+)$" },
  { "C++", "clang", REGEX_TYPE_EXTENSION, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*note:\\s*(?<message>.+)$" },
  { "C++", "clang", REGEX_TYPE_WARNING, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*warning:\\s*(?<message>.+)$" },
  { "C++", "gcc", REGEX_TYPE_ERROR, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*.*error:\\s*(?<message>.+)$" },
  { "C++", "gcc", REGEX_TYPE_WARNING, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):(?<columnNumber>\\d+):\\s*warning:\\s*(?<message>.+)$" },
  { "C++", "linker", REGEX_TYPE_ERROR, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):\\s*(?<message>undefined.*)$" },
  { "Java", "javac", REGEX_TYPE_ERROR, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):\\s*error:\\s*(?<message>.+)$" },
  { "Java", "javac", REGEX_TYPE_ERROR, "^(?<filePath>[^:]+):(?<lineNumber>\\d+):\\s*warning:\\s*(?<message>.+)$" },
  { "Make", "gmake", REGEX_TYPE_ENTER, "^.*Entering directory\\s+'(?<directory>[^']*)'\\s*$" },
  { "Make", "gmake", REGEX_TYPE_LEAVE, "^.*Leaving directory\\s+'(?<directory>[^']*)'\\s*$" },
  { "PHP", "php", REGEX_TYPE_ERROR, "^Parse error: parse error,\\s*(.*)\\s+in\\s+(?<filePath>.*)\\s+on line\\s+(?<lineNumber>[0-9]+)\\s+(?<message>.+)$" },
  { "PHP", "php", REGEX_TYPE_ERROR, "^Parse error: syntax error,\\s*(.*)\\s+in\\s+(?<filePath>.*)\\s+on line\\s+(?<lineNumber>[0-9]+)\\s+(?<message>.+)$" },
  { "Perl", "perl", REGEX_TYPE_ERROR, "^syntax error at\\s+(?<filePath>.*)\\s+line\\s+(?<lineNumber>[0-9]+),\\s+(?<message>.+)$" },
};
